{% set name = "sleepecg" %}
{% set version = "0.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07971f52af329598a95f3e3d36e227fbb82b0f1df8acab32abf5c1c7f6a94ea7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - numpy >=1.20.0
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - requests >=2.25.0
    - scipy >=1.7.0
    - tqdm >=4.60.0
    - PyYAML >=5.4.0
    - joblib >=1.0.0
    - matplotlib-base >=3.5.0
    - mne-base >=1.0.0
    - numba >=0.55.0  # [py<312]
    - tensorflow >=2.7.0  # [not win and py<312]
    - wfdb >=3.4.0
    - edfio >=0.1.1

test:
  imports:
    - sleepecg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://sleepecg.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for sleep stage classification using ECG data
  dev_url: https://github.com/cbrnr/sleepecg

extra:
  recipe-maintainers:
    - cbrnr
    - hoechenberger
    - larsoner
