{% set name = "sleepecg" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abfe07e0b90dae47d6bdfe13ee7d5dab6a8c3dcbbaf81191b4c3773744939598

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy 1.20.*
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - requests >=2.25.0
    - scipy >=1.6.0
    - tqdm >=4.59.0
    - numba >=0.53.0
    - pandas >=1.2.0
    - wfdb >=3.3.0
    - PyYAML >=5.4.0

test:
  imports:
    - sleepecg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://sleepecg.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A toolbox for sleep stage classification using ECG data
  dev_url: https://github.com/cbrnr/sleepecg

extra:
  recipe-maintainers:
    - hoechenberger
