{% set name = "sleepecg" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa49940bb2699bf781cb2968d0bbf3c0765756e5f3fafd9f3ccbbfc63a3595ae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - requests >=2.25.0
    - scipy >=1.7.0
    - tqdm >=4.60.0
    - numba >=0.55.0
    - pandas >=1.4.0
    - wfdb >=3.4.0
    - PyYAML >=5.4.0
    - joblib >=1.0.0
    - mne-base >=1.0.0
    - matplotlib-base >=3.5.0
    - tensorflow >=2.7.0  # [not win]

test:
  imports:
    - sleepecg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://sleepecg.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A toolbox for sleep stage classification using ECG data
  dev_url: https://github.com/cbrnr/sleepecg

extra:
  recipe-maintainers:
    - cbrnr
    - hoechenberger
    - larsoner
