{% set name = "sleepecg" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f15ee55ec5567e13cb57a99009d2fe8533702a32cbb4d24c0551fefd45e920ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - numpy
  run:
    - python
    - requests >=2.32.3
    - numpy >=1.26.0
    - scipy >=1.13.0
    - tqdm >=4.66.0
    - PyYAML >=6.0.0
    - joblib >=1.4.2
    - matplotlib-base >=3.9.2
    - mne-base >=1.0.0
    # needs https://github.com/conda-forge/numba-feedstock/pull/152
    - numba >=0.61.0  # [py<313]
    - tensorflow >=2.7.0  # [not win and not ppc64le and not aarch64 and py<313]
    - wfdb >=4.2.0
    # needs https://github.com/conda-forge/edfio-feedstock/pull/16
    - edfio >=0.4.4  # [py<313]

test:
  imports:
    - sleepecg
  requires:
    - pip
  commands:
    - pip check
    - python -c "import sleepecg; assert sleepecg.__version__ == '{{ version }}', sleepecg.__version__"

about:
  home: https://sleepecg.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for sleep stage classification using ECG data
  dev_url: https://github.com/cbrnr/sleepecg

extra:
  recipe-maintainers:
    - cbrnr
    - hoechenberger
    - larsoner
